### PR TITLE
Renaming analytics to metrics so privacy plugins won't interfere plus a typo fix

### PR DESCRIPTION
**Pull request by MrCsabaToth**
Some privacy/adblocker filters contain match for analytics.js, probably to block out Google analytics. If someone tries to visit the page, in the `footer-block.html` the `HOVERBOARD.Analytics.trackEvent('language', 'select', lang);` will barf cause the `HOVERBOARD.Analytics` won't be defined. As a result the screen remains blank. This simple rename PR avoids those filters (for example EasyPrivacy filter used by uBlock Origin or other adblockers would kick in).

### CODE REVIEW

**Comment by MrCsabaToth** [comment]
Added a typo fix

**Comment by MrCsabaToth** [comment]
Fixes #102

**Comment by MrCsabaToth** [comment]
Do I need to branch this?

**Comment by ozasadnyy** [comment]
Awesome @MrCsabaToth , many thanks for this fix!

**Comment by milosmns** [comment]
Nice catch. Strange how the blocker doesn't analyze the content though..

**Pull request merged**
