### PR TITLE
Develop

### LINKED ISSUE #123: Handling large number of ticket types and other ticket enhancements
1. More than 3-4 tickets are squash together into one row, no matter how many
2. Longer side content (example: "Student (early)") flows out of rectangle
3. On-site ticket has only one date

Proposed solutions in an upcoming PR:
1. Setting minimum width prevents squashing together and causes natural wrap
2. Allowing word wrap in side content helps the issue
3. Some templating solves this

### PR DESCRIPTION
**Pull request by MrCsabaToth**
Fixes #123

### CODE REVIEW

**Comment by tasomaniac** [comment]
Hi, 

It would be the best if you can put some explanation also in the pr. I saw you also put some screenshots in the issue. It would be the best to have before/after screenshots of the solution you provide. 

Thanks a lot. :+1:

**Comment by ozasadnyy** [comment]
Yeah, screenshots would be really nice (consider several screen sizes).

In any case, thanks for a contribution!

**Comment by ozasadnyy** [comment]
Hey @MrCsabaToth , just a reminder that we expect some screenshots before merging.

**Comment by MrCsabaToth** [comment]
Finally I simplified my ticket selection and got back down to 3 tickets again. The side content had another CSS solution to have more clearance, but that's only useful if you have longer side text. I'd need to craft another pull request maybe with the one date ticket and the CSS change.

**Pull request closed without merging**
