### PR TITLE
v1.0.3

### LINKED ISSUE #66: IE 11 Polyfills not working?
The [suggested method](https://www.polymer-project.org/1.0/docs/browsers) of checking if web components are supported in your browser is [already implemented](https://github.com/gdg-x/hoverboard/blob/master/app/scripts/app.js), but it doesnt seem to work. I get blank pages.

### LINKED ISSUE #119: Speaker popup is missing visual features when non of the skills are colored
I made up some skills when I filled out the speaker.json, and now I have more speakers who doesn't have any colored skill. When that happen most of the modal speaker dialog is white, and it's not obvious where is the close button (top left, it's white on white arrow).
speaker1
speaker2

### LINKED ISSUE #126: Caching problems
Whenever I deploy a new version onto our Firebase staging host, I have to manually clear the cache with a hard refresh (using Ctrl+F5 in Chrome for Linux).

I had expected that the cache would invalidate and the fresh version would load up the next time, but I've understood that due to offline availability of the site, a popup should instead appear at the bottom of the screen. I haven't seen this popup; what can I do to troubleshoot this?

### LINKED ISSUE #127: Filter is only working on Google Chrome
We received a bug report saying the Filter on Schedule page is not working.
I tested on Safari, Firefox and Edge.
screen shot 2016-09-08 at 12 05 58 pm

### LINKED ISSUE #131: Footer and some sections on the main page get condensed on Safari
Here's an example of devfestflorida.org's footer section which gets condensed on Safari on an iOS device. Can also replicate with Safari on a desktop by shrinking the width to around 600px (or any iPhone in portrait

image

### PR DESCRIPTION
**Pull request by ozasadnyy**
- Added support of Polymer CLI v0.16.0+
- Fixed schedule filters in other than Chrome browsers. Fixed #127
- Made it working in IE. Fixed #66
- Fixed flexbox bugs on Safari. Fixed #131
- Added fallback color for session/speakers dialog. Fixed #119
- Fixed analytics error for featured videos
- Fixed function declaration in blog-list element
- Removed firebase hosting caching. Fixed #126 
- Replaced `docment.write` with `insertBefore` for ES6 polyfill

### CODE REVIEW

**Comment by tasomaniac** [comment]
Wow! Great release. Congrats.

**Comment by matiaspunx** [comment]
Ty! Updated to latest release :)
Tomorrow I Will share our link

**Comment by tasomaniac** [comment]
@ozasadnyy Just a question. 
I've just updated GDG Istanbul's fork. When I open the website in Chrome, I still saw the old version. When I open in incognito windows I saw the new page. 

I saw some fixes regarding to the cache mechanism. That's why I'm asking. 

How can we make sure that users will get the latest site without forcing them to clear caches. 

Here is our [work in progress] website :)

**Comment by sophieH29** [comment]
@tasomaniac haven't toast appeared for you to refresh the content?
We've removed additional caching with Firebase; cause service worker has been doing that.

**Comment by ozasadnyy** [comment]
@tasomaniac as @sophieH29 said, we have removed Firebase server caching (sorry about that). Now after SW installs new version, toast with a refresh button should appear.

**Comment by tasomaniac** [comment]
Just to be clear. So, for the old version, this was a problem but from now on if we publish a new version, will it appear?

**Comment by ozasadnyy** [comment]
With Firebase caching SW didn't see a new version of files. That's why toast didn't appear.

**Pull request merged**
