### PR TITLE
Fix Schedule Day is not selected by default

### PR DESCRIPTION
**Pull request by echoAlexey**
- first days of schedule is not displayed by default when navigation to schedule happens

### CODE REVIEW

**Comment by ozasadnyy** [comment]
Thanks :)

**Comment by ozasadnyy** [comment]
@echoAlexey could you tell more about your issue? I had to revert your PR as it doesn't work and create an error

**Comment by echoAlexey** [comment]
Hi, yes. 

For some reason first day of schedule didn't get selected when navigating to `schedule` from nav bar. 
And this was solving the problem for us... 

In my scenario results were the following.
**Before patch:**
 setSubroute received value 0

**After patch:**
setSubroute received value 2018-05-30 which is date for schedule day.

**Comment by ozasadnyy** [comment]
could you show your schedule DB object from firebase?

**Comment by echoAlexey** [comment]
we have schedule array with days defined as 

```
{
      "date": "2018-05-30",
      "dateReadable": "May 30",
      "tracks": [
        {
          "title": "Room 1"
        },
        {
          "title": "Room 2"
        },
        {
          "title": "Room 3"
        },
        {
          "title": "Room 4"
        },
        {
          "title": "Room 5"
        }
      ],
      "timeslots": [
        {
          "startTime": "08:30",
          "endTime": "09:45",
          "sessions": [
            {
              "items": [
                101
              ]
            }
          ]
        },
        {
          "startTime": "09:45",
          "endTime": "10:10",
          "sessions": [
            {
              "items": [
                102
              ]
            }
          ]
        },
        {
          "startTime": "10:10",
          "endTime": "11:00",
          "sessions": [
            {
              "items": [
                103
              ]
            }
          ]
        },
        {
          "startTime": "11:00",
          "endTime": "11:30",
          "sessions": [
            {
              "items": [
                104
              ]
            }
          ]
        },
        {
          "startTime": "11:30",
          "endTime": "12:30",
          "sessions": [
            {
              "items": [
                111
              ]
            },
            {
              "items": [
                112
              ]
            },
            {
              "items": [
                113
              ]
            },
            {
              "items": [
                114
              ]
            },
            {
              "items": [
                115
              ]
            }
          ]
        },
        {
          "startTime": "12:30",
          "endTime": "13:30",
          "sessions": [
            {
              "items": [
                105
              ]
            }
          ]
        },
        {
          "startTime": "13:30",
          "endTime": "14:30",
          "sessions": [
            {
              "items": [
                121
              ]
            },
            {
              "items": [
                122
              ]
            },
            {
              "items": [
                123
              ]
            },
            {
              "items": [
                124
              ]
            },
            {
              "items": [
                125
              ]
            }
          ]
        },
        {
          "startTime": "14:30",
          "endTime": "15:30",
          "sessions": [
            {
              "items": [
                131
              ]
            },
            {
              "items": [
                132
              ]
            },
            {
              "items": [
                133
              ]
            },
            {
              "items": [
                134
              ]
            },
            {
              "items": [
                135
              ]
            }
          ]
        },
        {
          "startTime": "15:30",
          "endTime": "16:00",
          "sessions": [
            {
              "items": [
                106
              ]
            }
          ]
        },
        {
          "startTime": "16:00",
          "endTime": "17:00",
          "sessions": [
            {
              "items": [
                141
              ]
            },
            {
              "items": [
                142
              ]
            },
            {
              "items": [
                143
              ]
            },
            {
              "items": [
                144
              ]
            },
            {
              "items": [
                145
              ]
            }
          ]
        },
        {
          "startTime": "17:00",
          "endTime": "18:00",
          "sessions": [
            {
              "items": [
                151
              ]
            },
            {
              "items": [
                152
              ]
            },
            {
              "items": [
                153
              ]
            },
            {
              "items": [
                154
              ]
            },
            {
              "items": [
                155
              ]
            }
          ]
        },
        {
          "startTime": "18:00",
          "endTime": "19:00",
          "sessions": [
            {
              "items": [
                161
              ]
            },
            {
              "items": [
                162
              ]
            },
            {
              "items": [
                163
              ]
            },
            {
              "items": [
                164
              ]
            },
            {
              "items": [
                165
              ]
            }
          ]
        },
        {
          "startTime": "19:00",
          "endTime": "24:00",
          "sessions": [
            {
              "items": [
                107
              ]
            }
          ]
        }
      ]
    }
```

**Comment by ozasadnyy** [comment]
Well, that's a problem. A schedule is an object and should look like this:
hoverboard-v2-dev database firebase console 2018-01-16 14-01-40

**Comment by echoAlexey** [comment]
Thanks! Will do the fix for our structure.

**Pull request merged**
