### PR TITLE
Add schedule

### PR DESCRIPTION
**Pull request by friedger**
This PR adds a basic schedule.
The sessions should contain a time property, they can also have tags.
Sessions are sorted by time

### CODE REVIEW

**Comment by ozasadnyy** [comment]
Sorry, I have already created base structure for schedule on my local machine and it have much different design. This approach will not work for conferences with parallel streams...

**Comment by friedger** [comment]
I can work with the filter, but hey, go ahead. We just needed a quick solution for #11

**Comment by twhetzel** [comment]
@ozasadnyy What's the element name for the schedule/is it committed to the repo?

**Comment by ozasadnyy** [comment]
@twhetzel no, it's still in development

**Pull request closed without merging**
