### PR TITLE
dev Dockerfile

### PR DESCRIPTION
**Pull request by tivvit**
Hi,

I created Dockerfile for this project.
Why? Because when I tried to contribute, I had problems with old version of node (because I do not normally use it). 

The usage is very simple:
```shell
# build the image
docker build -t hoverboard .

# run
docker run -it -v "$PWD":/app -p 8080:8080 hoverboard
# now you can develop locally without bothering with versions or installing anything

# build
docker run -v "$PWD":/app hoverboard polymer build
# deploy with firebase
```

### CODE REVIEW

**Comment by ozasadnyy** [comment]
Wow, looks amazing! Could you add docs how to use it here https://github.com/gdg-x/hoverboard/tree/master/docs and reference in https://github.com/gdg-x/hoverboard/blob/master/README.md ?

**Comment by ozasadnyy** [comment]
@tivvit just a kind reminder :)

**Comment by tivvit** [comment]
I am sorry I had no time, I hope i will prepare it today ;)

**Comment by idvoretskyi** [comment]
Coding part LGTM, dockerizing the application is absolutely useful. 

Thank you, @tivvit

**Comment by tivvit** [comment]
Finally! I had time to work on this thanks to GDE CEE summit. I hope it is ok.

**Comment by ndrwtrsk** [comment]
I think I saw you coding this ;)

**Comment by ozasadnyy** [comment]
Thanks a lot! People will love it :)

**Pull request merged**
